# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ko-KR
reviews:
  profile: chill
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - develop
